# go-cqhttp 配置文件
# QQ机器人: 102873100

account:
  uin: 102873100
  password: 'MNOPQRSTVXZbdfhknqtwz26AEIMQUYdi'
  encrypt: false
  status: 0
  relogin:
    delay: 3
    interval: 3
    max-times: 0
  
heartbeat:
  interval: 5

message:
  post-format: string
  ignore-invalid-cqcode: false
  force-fragment: false
  fix-url: false
  proxy-rewrite: ''
  report-self-message: false
  remove-reply-at: false
  extra-reply-data: false
  skip-mime-scan: false
  
output:
  log-level: info
  log-aging: 15
  log-force-new: true
  log-colorful: true
  debug: false
  
servers:
  - http:
      host: 0.0.0.0
      port: 5700
      timeout: 30
      post:
        - url: http://192.168.0.238:8080/qq/callback
          secret: ''
          max-retries: 3
          retries-interval: 1500
      middlewares:
        <<: *default
        access-token: ''
